const { PROPS } = require('./ingredient_props');

exports.ingredients = {
  'abecean longfin': {
    name: 'abecean longfin',
    props: [
      PROPS.WEAKNESS_TO_FROST,
      PROPS.FORTIFY_SNEAK,
      PROPS.WEAKNESS_TO_POISON,
      PROPS.FORTIFY_RESTORATION,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.5,
    value: 15,
  },
  'bear claws': {
    name: 'bear claws',
    props: [
      PROPS.RESTORE_STAMINA,
      PROPS.FORTIFY_HEALTH,
      PROPS.FORTIFY_ONE_HANDED,
      PROPS.DAMAGE_MAGICKA_REGEN,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.1,
    value: 2,
  },
  'bee': {
    name: 'bee',
    props: [
      PROPS.RESTORE_STAMINA,
      PROPS.RAVAGE_STAMINA,
      PROPS.REGEN_STAMINA,
      PROPS.WEAKNESS_TO_SHOCK,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.1,
    value: 3,
  },
  'beehive husk': {
    name: 'beehive husk',
    props: [
      PROPS.RESIST_POISON,
      PROPS.FORTIFY_LIGHT_ARMOR,
      PROPS.FORTIFY_SNEAK,
      PROPS.FORTIFY_DESTRUCTION,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 1,
    value: 5,
  },
  'berit\'s ashes': {
    name: 'berit\'s ashes',
    props: [
      PROPS.DAMAGE_STAMINA,
      PROPS.RESIST_FIRE,
      PROPS.FORTIFY_CONJURATION,
      PROPS.RAVAGE_STAMINA,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.2,
    value: 5,
  },
  'bleeding crown': {
    name: 'bleeding crown',
    props: [
      PROPS.WEAKNESS_TO_FIRE,
      PROPS.FORTIFY_BLOCK,
      PROPS.WEAKNESS_TO_POISON,
      PROPS.RESIST_MAGIC,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.3,
    value: 10,
  },
  'blisterwort': {
    name: 'blisterwort',
    props: [
      PROPS.DAMAGE_STAMINA,
      PROPS.FRENZY,
      PROPS.RESTORE_HEALTH,
      PROPS.FORTIFY_SMITHING,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.2,
    value: 12,
  },
  'blue butterfly wing': {
    name: 'blue butterfly wing',
    props: [
      PROPS.DAMAGE_STAMINA,
      PROPS.FORTIFY_CONJURATION,
      PROPS.DAMAGE_MAGICKA_REGEN,
      PROPS.FORTIFY_ENCHANTING,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.1,
    value: 2,
  },
  'blue dartwing': {
    name: 'blue dartwing',
    props: [
      PROPS.RESIST_SHOCK,
      PROPS.FORTIFY_PICKPOCKET,
      PROPS.RESTORE_HEALTH,
      PROPS.FEAR,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.1,
    value: 1,
  },
  'blue mountain flower': {
    name: 'blue mountain flower',
    props: [
      PROPS.RESTORE_HEALTH,
      PROPS.FORTIFY_CONJURATION,
      PROPS.FORTIFY_HEALTH,
      PROPS.DAMAGE_MAGICKA_REGEN,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.1,
    value: 2,
  },
  'bone meal': {
    name: 'bone meal',
    props: [
      PROPS.DAMAGE_STAMINA,
      PROPS.RESIST_FIRE,
      PROPS.FORTIFY_CONJURATION,
      PROPS.RAVAGE_STAMINA,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.5,
    value: 5,
  },
  'briar heart': {
    name: 'briar heart',
    props: [
      PROPS.RESTORE_MAGICKA,
      PROPS.FORTIFY_BLOCK,
      PROPS.PARALYSIS,
      PROPS.FORTIFY_MAGICKA,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.5,
    value: 20,
  },
  'butterfly wing': {
    name: 'butterfly wing',
    props: [
      PROPS.RESTORE_HEALTH,
      PROPS.FORTIFY_BARTER,
      PROPS.LINGER_DAMAGE_STAMINA,
      PROPS.DAMAGE_MAGICKA,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.1,
    value: 3,
  },
  'canis root': {
    name: 'canis root',
    props: [
      PROPS.DAMAGE_STAMINA,
      PROPS.FORTIFY_ONE_HANDED,
      PROPS.FORTIFY_MARKSMAN,
      PROPS.PARALYSIS,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.1,
    value: 5,
  },
  'charred skeever hide': {
    name: 'charred skeever hide',
    props: [
      PROPS.RESTORE_STAMINA,
      PROPS.CURE_DISEASE,
      PROPS.RESIST_POISON,
      PROPS.RESTORE_HEALTH,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.5,
    value: 1,
  },
  'chaurus eggs': {
    name: 'chaurus eggs',
    props: [
      PROPS.WEAKNESS_TO_POISON,
      PROPS.FORTIFY_STAMINA,
      PROPS.DAMAGE_MAGICKA,
      PROPS.INVISIBILITY,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.2,
    value: 10,
  },
  'chicken\'s egg': {
    name: 'chicken\'s egg',
    props: [
      PROPS.RESIST_MAGIC,
      PROPS.DAMAGE_MAGICKA_REGEN,
      PROPS.WATERBREATHING,
      PROPS.LINGER_DAMAGE_STAMINA,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.5,
    value: 2,
  },
  'creep cluster': {
    name: 'creep cluster',
    props: [
      PROPS.RESTORE_MAGICKA,
      PROPS.DAMAGE_STAMINA_REGEN,
      PROPS.FORTIFY_CARRY_WEIGHT,
      PROPS.WEAKNESS_TO_MAGIC,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.2,
    value: 1,
  },
  'crimson nirnroot': {
    name: 'crimson nirnroot',
    props: [
      PROPS.DAMAGE_HEALTH,
      PROPS.DAMAGE_STAMINA,
      PROPS.INVISIBILITY,
      PROPS.RESIST_MAGIC,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.2,
    value: 10,
  },
  'cyrodilic spadetail': {
    name: 'cyrodilic spadetail',
    props: [
      PROPS.DAMAGE_STAMINA,
      PROPS.FORTIFY_RESTORATION,
      PROPS.FEAR,
      PROPS.RAVAGE_HEALTH,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.25,
    value: 15,
  },
  'daedra heart': {
    name: 'daedra heart',
    props: [
      PROPS.RESTORE_HEALTH,
      PROPS.DAMAGE_STAMINA_REGEN,
      PROPS.DAMAGE_MAGICKA,
      PROPS.FEAR,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.5,
    value: 250,
  },
  'deathbell': {
    name: 'deathbell',
    props: [
      PROPS.DAMAGE_HEALTH,
      PROPS.RAVAGE_STAMINA,
      PROPS.SLOW,
      PROPS.WEAKNESS_TO_POISON,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.1,
    value: 4,
  },
  'dragon\'s tongue': {
    name: 'dragon\'s tongue',
    props: [
      PROPS.RESIST_FIRE,
      PROPS.FORTIFY_BARTER,
      PROPS.FORTIFY_ILLUSION,
      PROPS.FORTIFY_TWO_HANDED,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.1,
    value: 5,
  },
  'dwarven oil': {
    name: 'dwarven oil',
    props: [
      PROPS.WEAKNESS_TO_MAGIC,
      PROPS.FORTIFY_ILLUSION,
      PROPS.REGEN_MAGICKA,
      PROPS.RESTORE_MAGICKA,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.25,
    value: 15,
  },
  'ectoplasm': {
    name: 'ectoplasm',
    props: [
      PROPS.RESTORE_MAGICKA,
      PROPS.FORTIFY_DESTRUCTION,
      PROPS.FORTIFY_MAGICKA,
      PROPS.DAMAGE_HEALTH,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.1,
    value: 25,
  },
  'elves ear': {
    name: 'elves ear',
    props: [
      PROPS.RESTORE_MAGICKA,
      PROPS.FORTIFY_MARKSMAN,
      PROPS.WEAKNESS_TO_FROST,
      PROPS.RESIST_FIRE,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.1,
    value: 10,
  },
  'eye of sabre cat': {
    name: 'eye of sabre cat',
    props: [
      PROPS.RESTORE_STAMINA,
      PROPS.RAVAGE_HEALTH,
      PROPS.DAMAGE_MAGICKA,
      PROPS.RESTORE_HEALTH,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.1,
    value: 2,
  },
  'falmer ear': {
    name: 'falmer ear',
    props: [
      PROPS.DAMAGE_HEALTH,
      PROPS.FRENZY,
      PROPS.RESIST_POISON,
      PROPS.FORTIFY_LOCKPICKING,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.2,
    value: 10,
  },
  'fire salts': {
    name: 'fire salts',
    props: [
      PROPS.WEAKNESS_TO_FROST,
      PROPS.RESIST_FIRE,
      PROPS.RESTORE_MAGICKA,
      PROPS.REGEN_MAGICKA,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.25,
    value: 50,
  },
  'fly amanita': {
    name: 'fly amanita',
    props: [
      PROPS.RESIST_FIRE,
      PROPS.FORTIFY_TWO_HANDED,
      PROPS.FRENZY,
      PROPS.REGEN_STAMINA,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.1,
    value: 2,
  },
  'frost mirriam': {
    name: 'frost mirriam',
    props: [
      PROPS.RESIST_FROST,
      PROPS.FORTIFY_SNEAK,
      PROPS.RAVAGE_MAGICKA,
      PROPS.DAMAGE_STAMINA_REGEN,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.1,
    value: 1,
  },
  'frost salts': {
    name: 'frost salts',
    props: [
      PROPS.WEAKNESS_TO_FIRE,
      PROPS.RESIST_FROST,
      PROPS.RESTORE_MAGICKA,
      PROPS.FORTIFY_CONJURATION,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.25,
    value: 100,
  },
  'garlic': {
    name: 'garlic',
    props: [
      PROPS.RESIST_POISON,
      PROPS.FORTIFY_STAMINA,
      PROPS.REGEN_MAGICKA,
      PROPS.REGEN_HEALTH,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.25,
    value: 1,
  },
  'giant lichen': {
    name: 'giant lichen',
    props: [
      PROPS.WEAKNESS_TO_SHOCK,
      PROPS.RAVAGE_HEALTH,
      PROPS.WEAKNESS_TO_POISON,
      PROPS.RESTORE_MAGICKA,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.25,
    value: 5,
  },
  'giant\'s toe': {
    name: 'giant\'s toe',
    props: [
      PROPS.DAMAGE_STAMINA,
      PROPS.FORTIFY_HEALTH,
      PROPS.FORTIFY_CARRY_WEIGHT,
      PROPS.DAMAGE_STAMINA_REGEN,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 1,
    value: 20,
  },
  'glow dust': {
    name: 'glow dust',
    props: [
      PROPS.DAMAGE_MAGICKA,
      PROPS.DAMAGE_MAGICKA_REGEN,
      PROPS.FORTIFY_DESTRUCTION,
      PROPS.RESIST_SHOCK,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.5,
    value: 20,
  },
  'glowing mushroom': {
    name: 'glowing mushroom',
    props: [
      PROPS.RESIST_SHOCK,
      PROPS.FORTIFY_DESTRUCTION,
      PROPS.FORTIFY_SMITHING,
      PROPS.FORTIFY_HEALTH,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.2,
    value: 5,
  },
  'grass pod': {
    name: 'grass pod',
    props: [
      PROPS.RESIST_POISON,
      PROPS.RAVAGE_MAGICKA,
      PROPS.FORTIFY_ALTERATION,
      PROPS.RESTORE_MAGICKA,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.1,
    value: 1,
  },
  'hagraven claw': {
    name: 'hagraven claw',
    props: [
      PROPS.RESIST_MAGIC,
      PROPS.LINGER_DAMAGE_MAGICKA,
      PROPS.FORTIFY_ENCHANTING,
      PROPS.FORTIFY_BARTER,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.25,
    value: 20,
  },
  'hagraven feathers': {
    name: 'hagraven feathers',
    props: [
      PROPS.DAMAGE_MAGICKA,
      PROPS.FORTIFY_CONJURATION,
      PROPS.FRENZY,
      PROPS.WEAKNESS_TO_SHOCK,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.1,
    value: 20,
  },
  'hanging moss': {
    name: 'hanging moss',
    props: [
      PROPS.DAMAGE_MAGICKA,
      PROPS.FORTIFY_HEALTH,
      PROPS.DAMAGE_MAGICKA_REGEN,
      PROPS.FORTIFY_ONE_HANDED,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.25,
    value: 1,
  },
  'hawk beak': {
    name: 'hawk beak',
    props: [
      PROPS.RESTORE_STAMINA,
      PROPS.RESIST_FROST,
      PROPS.FORTIFY_CARRY_WEIGHT,
      PROPS.RESIST_SHOCK,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.25,
    value: 15,
  },
  'hawk feathers': {
    name: 'hawk feathers',
    props: [
      PROPS.CURE_DISEASE,
      PROPS.FORTIFY_LIGHT_ARMOR,
      PROPS.FORTIFY_ONE_HANDED,
      PROPS.FORTIFY_SNEAK,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.1,
    value: 15,
  },
  'histcarp': {
    name: 'histcarp',
    props: [
      PROPS.RESTORE_STAMINA,
      PROPS.FORTIFY_MAGICKA,
      PROPS.DAMAGE_STAMINA_REGEN,
      PROPS.WATERBREATHING,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.25,
    value: 6,
  },
  'honeycomb': {
    name: 'honeycomb',
    props: [
      PROPS.RESTORE_STAMINA,
      PROPS.FORTIFY_BLOCK,
      PROPS.FORTIFY_LIGHT_ARMOR,
      PROPS.RAVAGE_STAMINA,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 1,
    value: 5,
  },
  'human flesh': {
    name: 'human flesh',
    props: [
      PROPS.DAMAGE_HEALTH,
      PROPS.PARALYSIS,
      PROPS.RESTORE_MAGICKA,
      PROPS.FORTIFY_SNEAK,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.25,
    value: 1,
  },
  'human heart': {
    name: 'human heart',
    props: [
      PROPS.DAMAGE_HEALTH,
      PROPS.DAMAGE_MAGICKA,
      PROPS.DAMAGE_MAGICKA_REGEN,
      PROPS.FRENZY,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 1,
    value: 0,
  },
  'ice wraith teeth': {
    name: 'ice wraith teeth',
    props: [
      PROPS.WEAKNESS_TO_FROST,
      PROPS.FORTIFY_HEAVY_ARMOR,
      PROPS.INVISIBILITY,
      PROPS.WEAKNESS_TO_FIRE,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.25,
    value: 30,
  },
  'imp stool': {
    name: 'imp stool',
    props: [
      PROPS.DAMAGE_HEALTH,
      PROPS.LINGER_DAMAGE_HEALTH,
      PROPS.PARALYSIS,
      PROPS.RESTORE_HEALTH,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.3,
    value: 0,
  },
  'jarrin root': {
    name: 'jarrin root',
    props: [
      PROPS.DAMAGE_HEALTH,
      PROPS.DAMAGE_MAGICKA,
      PROPS.DAMAGE_STAMINA,
      PROPS.DAMAGE_MAGICKA_REGEN,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.5,
    value: 10,
  },
  'jazbay grapes': {
    name: 'jazbay grapes',
    props: [
      PROPS.WEAKNESS_TO_MAGIC,
      PROPS.FORTIFY_MAGICKA,
      PROPS.REGEN_MAGICKA,
      PROPS.RAVAGE_HEALTH,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.2,
    value: 1,
  },
  'juniper berries': {
    name: 'juniper berries',
    props: [
      PROPS.WEAKNESS_TO_FIRE,
      PROPS.FORTIFY_MARKSMAN,
      PROPS.REGEN_HEALTH,
      PROPS.DAMAGE_STAMINA_REGEN,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.1,
    value: 1,
  },
  'large antlers': {
    name: 'large antlers',
    props: [
      PROPS.RESTORE_STAMINA,
      PROPS.FORTIFY_STAMINA,
      PROPS.SLOW,
      PROPS.DAMAGE_STAMINA_REGEN,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.1,
    value: 2,
  },
  'lavender': {
    name: 'lavender',
    props: [
      PROPS.RESIST_MAGIC,
      PROPS.FORTIFY_STAMINA,
      PROPS.RAVAGE_MAGICKA,
      PROPS.FORTIFY_CONJURATION,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.1,
    value: 1,
  },
  'luna moth wing': {
    name: 'luna moth wing',
    props: [
      PROPS.DAMAGE_MAGICKA,
      PROPS.FORTIFY_LIGHT_ARMOR,
      PROPS.REGEN_HEALTH,
      PROPS.INVISIBILITY,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.1,
    value: 5,
  },
  'moon sugar': {
    name: 'moon sugar',
    props: [
      PROPS.WEAKNESS_TO_FIRE,
      PROPS.RESIST_FROST,
      PROPS.RESTORE_MAGICKA,
      PROPS.REGEN_MAGICKA,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.25,
    value: 50,
  },
  'mora tapinella': {
    name: 'mora tapinella',
    props: [
      PROPS.RESTORE_MAGICKA,
      PROPS.LINGER_DAMAGE_HEALTH,
      PROPS.REGEN_STAMINA,
      PROPS.FORTIFY_ILLUSION,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.25,
    value: 4,
  },
  'mudcrab chitin': {
    name: 'mudcrab chitin',
    props: [
      PROPS.RESTORE_STAMINA,
      PROPS.CURE_DISEASE,
      PROPS.RESIST_POISON,
      PROPS.RESIST_FIRE,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.25,
    value: 2,
  },
  'namira\'s rot': {
    name: 'namira\'s rot',
    props: [
      PROPS.DAMAGE_MAGICKA,
      PROPS.FORTIFY_LOCKPICKING,
      PROPS.FEAR,
      PROPS.REGEN_HEALTH,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.25,
    value: 0,
  },
  'nightshade': {
    name: 'nightshade',
    props: [
      PROPS.DAMAGE_HEALTH,
      PROPS.DAMAGE_MAGICKA_REGEN,
      PROPS.LINGER_DAMAGE_STAMINA,
      PROPS.FORTIFY_DESTRUCTION,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.1,
    value: 8,
  },
  'nirnroot': {
    name: 'nirnroot',
    props: [
      PROPS.DAMAGE_HEALTH,
      PROPS.DAMAGE_MAGICKA_REGEN,
      PROPS.INVISIBILITY,
      PROPS.RESIST_MAGIC,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.2,
    value: 10,
  },
  'nordic barnacle': {
    name: 'nordic barnacle',
    props: [
      PROPS.DAMAGE_MAGICKA,
      PROPS.WATERBREATHING,
      PROPS.REGEN_HEALTH,
      PROPS.FORTIFY_PICKPOCKET,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.2,
    value: 5,
  },
  'orange dartwing': {
    name: 'orange dartwing',
    props: [
      PROPS.RESTORE_STAMINA,
      PROPS.RAVAGE_MAGICKA,
      PROPS.FORTIFY_PICKPOCKET,
      PROPS.LINGER_DAMAGE_HEALTH,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.1,
    value: 1,
  },
  'pearl': {
    name: 'pearl',
    props: [
      PROPS.RESTORE_STAMINA,
      PROPS.FORTIFY_BLOCK,
      PROPS.RESTORE_MAGICKA,
      PROPS.RESIST_SHOCK,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.1,
    value: 1,
  },
  'pine thrush egg': {
    name: 'pine thrush egg',
    props: [
      PROPS.RESTORE_STAMINA,
      PROPS.FORTIFY_LOCKPICKING,
      PROPS.WEAKNESS_TO_POISON,
      PROPS.RESIST_SHOCK,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.5,
    value: 2,
  },
  'powdered mammoth tusk': {
    name: 'powdered mammoth tusk',
    props: [
      PROPS.RESTORE_STAMINA,
      PROPS.FORTIFY_SNEAK,
      PROPS.WEAKNESS_TO_FIRE,
      PROPS.FEAR,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.1,
    value: 2,
  },
  'purple mountain flower': {
    name: 'purple mountain flower',
    props: [
      PROPS.RESTORE_STAMINA,
      PROPS.FORTIFY_SNEAK,
      PROPS.LINGER_DAMAGE_MAGICKA,
      PROPS.RESIST_FROST,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.1,
    value: 2,
  },
  'red mountain flower': {
    name: 'red mountain flower',
    props: [
      PROPS.RESTORE_MAGICKA,
      PROPS.RAVAGE_MAGICKA,
      PROPS.FORTIFY_MAGICKA,
      PROPS.DAMAGE_HEALTH,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.1,
    value: 2,
  },
  'river betty': {
    name: 'river betty',
    props: [
      PROPS.DAMAGE_HEALTH,
      PROPS.FORTIFY_ALTERATION,
      PROPS.SLOW,
      PROPS.FORTIFY_CARRY_WEIGHT,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.25,
    value: 15,
  },
  'rock warbler egg': {
    name: 'rock warbler egg',
    props: [
      PROPS.RESTORE_HEALTH,
      PROPS.FORTIFY_ONE_HANDED,
      PROPS.DAMAGE_STAMINA,
      PROPS.WEAKNESS_TO_MAGIC,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.5,
    value: 2,
  },
  'sabre cat tooth': {
    name: 'sabre cat tooth',
    props: [
      PROPS.RESTORE_STAMINA,
      PROPS.FORTIFY_HEAVY_ARMOR,
      PROPS.FORTIFY_SMITHING,
      PROPS.WEAKNESS_TO_POISON,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.1,
    value: 2,
  },
  'salt pile': {
    name: 'salt pile',
    props: [
      PROPS.WEAKNESS_TO_MAGIC,
      PROPS.FORTIFY_RESTORATION,
      PROPS.SLOW,
      PROPS.REGEN_MAGICKA,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.2,
    value: 2,
  },
  'scaly pholiota': {
    name: 'scaly pholiota',
    props: [
      PROPS.WEAKNESS_TO_MAGIC,
      PROPS.FORTIFY_ILLUSION,
      PROPS.REGEN_STAMINA,
      PROPS.FORTIFY_CARRY_WEIGHT,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.25,
    value: 4,
  },
  'silverside perch': {
    name: 'silverside perch',
    props: [
      PROPS.RESTORE_STAMINA,
      PROPS.DAMAGE_STAMINA_REGEN,
      PROPS.RAVAGE_HEALTH,
      PROPS.RESIST_FROST,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.25,
    value: 15,
  },
  'skeever tail': {
    name: 'skeever tail',
    props: [
      PROPS.DAMAGE_STAMINA_REGEN,
      PROPS.RAVAGE_HEALTH,
      PROPS.DAMAGE_HEALTH,
      PROPS.FORTIFY_LIGHT_ARMOR,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.2,
    value: 3,
  },
  'slaughterfish egg': {
    name: 'slaughterfish egg',
    props: [
      PROPS.RESIST_POISON,
      PROPS.FORTIFY_PICKPOCKET,
      PROPS.LINGER_DAMAGE_HEALTH,
      PROPS.FORTIFY_STAMINA,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.2,
    value: 3,
  },
  'slaughterfish scales': {
    name: 'slaughterfish scales',
    props: [
      PROPS.RESIST_FROST,
      PROPS.LINGER_DAMAGE_HEALTH,
      PROPS.FORTIFY_HEAVY_ARMOR,
      PROPS.FORTIFY_BLOCK,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.1,
    value: 3,
  },
  'small antlers': {
    name: 'small antlers',
    props: [
      PROPS.WEAKNESS_TO_POISON,
      PROPS.FORTIFY_RESTORATION,
      PROPS.LINGER_DAMAGE_STAMINA,
      PROPS.DAMAGE_HEALTH,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.1,
    value: 2,
  },
  'small pearl': {
    name: 'small pearl',
    props: [
      PROPS.RESTORE_STAMINA,
      PROPS.FORTIFY_ONE_HANDED,
      PROPS.FORTIFY_RESTORATION,
      PROPS.RESIST_FROST,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.1,
    value: 2,
  },
  'snowberries': {
    name: 'snowberries',
    props: [
      PROPS.RESIST_FIRE,
      PROPS.FORTIFY_ENCHANTING,
      PROPS.RESIST_FROST,
      PROPS.RESIST_SHOCK,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.1,
    value: 4,
  },
  'spider egg': {
    name: 'spider egg',
    props: [
      PROPS.DAMAGE_STAMINA,
      PROPS.DAMAGE_MAGICKA_REGEN,
      PROPS.FORTIFY_LOCKPICKING,
      PROPS.FORTIFY_MARKSMAN,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.2,
    value: 5,
  },
  'spriggan sap': {
    name: 'spriggan sap',
    props: [
      PROPS.DAMAGE_MAGICKA_REGEN,
      PROPS.FORTIFY_ENCHANTING,
      PROPS.FORTIFY_SMITHING,
      PROPS.FORTIFY_ALTERATION,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.2,
    value: 15,
  },
  'swamp fungal pod': {
    name: 'swamp fungal pod',
    props: [
      PROPS.RESIST_SHOCK,
      PROPS.LINGER_DAMAGE_MAGICKA,
      PROPS.PARALYSIS,
      PROPS.RESTORE_HEALTH,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.25,
    value: 5,
  },
  'taproot': {
    name: 'taproot',
    props: [
      PROPS.WEAKNESS_TO_MAGIC,
      PROPS.FORTIFY_ILLUSION,
      PROPS.REGEN_MAGICKA,
      PROPS.RESTORE_MAGICKA,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.5,
    value: 15,
  },
  'thistle branch': {
    name: 'thistle branch',
    props: [
      PROPS.RESIST_FROST,
      PROPS.RAVAGE_STAMINA,
      PROPS.RESIST_POISON,
      PROPS.FORTIFY_HEAVY_ARMOR,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.1,
    value: 1,
  },
  'torchbug thorax': {
    name: 'torchbug thorax',
    props: [
      PROPS.RESTORE_STAMINA,
      PROPS.LINGER_DAMAGE_MAGICKA,
      PROPS.WEAKNESS_TO_MAGIC,
      PROPS.FORTIFY_STAMINA,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.1,
    value: 1,
  },
  'troll fat': {
    name: 'troll fat',
    props: [
      PROPS.RESIST_POISON,
      PROPS.FORTIFY_TWO_HANDED,
      PROPS.FRENZY,
      PROPS.DAMAGE_HEALTH,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 1,
    value: 15,
  },
  'tundra cotton': {
    name: 'tundra cotton',
    props: [
      PROPS.RESIST_MAGIC,
      PROPS.FORTIFY_MAGICKA,
      PROPS.FORTIFY_BLOCK,
      PROPS.FORTIFY_BARTER,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.1,
    value: 1,
  },
  'vampire dust': {
    name: 'vampire dust',
    props: [
      PROPS.INVISIBILITY,
      PROPS.RESTORE_MAGICKA,
      PROPS.REGEN_HEALTH,
      PROPS.CURE_DISEASE,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.2,
    value: 25,
  },
  'void salts': {
    name: 'void salts',
    props: [
      PROPS.WEAKNESS_TO_SHOCK,
      PROPS.RESTORE_MAGICKA,
      PROPS.DAMAGE_HEALTH,
      PROPS.FORTIFY_MAGICKA,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.2,
    value: 125,
  },
  'wheat': {
    name: 'wheat',
    props: [
      PROPS.RESTORE_HEALTH,
      PROPS.FORTIFY_HEALTH,
      PROPS.DAMAGE_STAMINA_REGEN,
      PROPS.LINGER_DAMAGE_MAGICKA,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.1,
    value: 5,
  },
  'white cap': {
    name: 'white cap',
    props: [
      PROPS.WEAKNESS_TO_FROST,
      PROPS.FORTIFY_HEAVY_ARMOR,
      PROPS.RESTORE_MAGICKA,
      PROPS.RAVAGE_MAGICKA,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.3,
    value: 0,
  },
  'wisp wrappings': {
    name: 'wisp wrappings',
    props: [
      PROPS.RESTORE_STAMINA,
      PROPS.FORTIFY_DESTRUCTION,
      PROPS.FORTIFY_CARRY_WEIGHT,
      PROPS.RESIST_MAGIC,
    ],
    multipliers: [1, 1, 1, 1],
    weight: 0.1,
    value: 2,
  },
};