exports.PROPS = {
  CURE_DISEASE: 'cure disease',
  CURE_POSION: 'cure poison',
  DAMAGE_HEALTH: 'damage health',
  DAMAGE_MAGICKA: 'damage magicka',
  DAMAGE_MAGICKA_REGEN: 'damage magicka regen',
  DAMAGE_STAMINA: 'damage stamina',
  DAMAGE_STAMINA_REGEN: 'damage stamina regen',
  FEAR: 'fear',
  FORTIFY_ALTERATION: 'fortify alteration',
  FORTIFY_BARTER: 'fortify barter',
  FORTIFY_BLOCK: 'fortify block',
  FORTIFY_CARRY_WEIGHT: 'fortify carry weight',
  FORTIFY_CONJURATION: 'fortify conjuration',
  FORTIFY_DESTRUCTION: 'fortify destruction',
  FORTIFY_ENCHANTING: 'fortify enchanting',
  FORTIFY_HEALTH: 'fortify health',
  FORTIFY_HEAVY_ARMOR: 'fortify heavy armor',
  FORTIFY_ILLUSION: 'fortify illusion',
  FORTIFY_LIGHT_ARMOR: 'fortify light armor',
  FORTIFY_LOCKPICKING: 'fortify lockpicking',
  FORTIFY_MAGICKA: 'fortify magicka',
  FORTIFY_MARKSMAN: 'fortify marksman',
  FORTIFY_ONE_HANDED: 'fortify one-handed',
  FORTIFY_PICKPOCKET: 'fortify pickpocket',
  FORTIFY_RESTORATION: 'fortify restoration',
  FORTIFY_SMITHING: 'fortify smithing',
  FORTIFY_SNEAK: 'fortify sneak',
  FORTIFY_STAMINA: 'fortify stamina',
  FORTIFY_TWO_HANDED: 'fortify two-handed',
  FRENZY: 'frenzy',
  INVISIBILITY: 'invisibility',
  LINGER_DAMAGE_HEALTH: 'lingering damage health',
  LINGER_DAMAGE_MAGICKA: 'lingering damage magicka',
  LINGER_DAMAGE_STAMINA: 'lingering damage stamina',
  PARALYSIS: 'paralysis',
  RAVAGE_HEALTH: 'ravage health',
  RAVAGE_MAGICKA: 'ravage magicka',
  RAVAGE_STAMINA: 'ravage stamina',
  REGEN_HEALTH: 'regenerate health',
  REGEN_MAGICKA: 'regenerate magicka',
  REGEN_STAMINA: 'regenerate stamina',
  RESIST_FIRE: 'resist fire',
  RESIST_FROST: 'resist frost',
  RESIST_MAGIC: 'resist magic',
  RESIST_POISON: 'resist poison',
  RESIST_SHOCK: 'resist shock',
  RESTORE_HEALTH: 'restore health',
  RESTORE_MAGICKA: 'restore magicka',
  RESTORE_STAMINA: 'restore stamina',
  SLOW: 'slow',
  WATERBREATHING: 'waterbreathing',
  WEAKNESS_TO_FIRE: 'weakness to fire',
  WEAKNESS_TO_FROST: 'weakness to frost',
  WEAKNESS_TO_MAGIC: 'weakness to magic',
  WEAKNESS_TO_POISON: 'weakness to poison',
  WEAKNESS_TO_SHOCK: 'weakness to shock',
};
